# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ensemble_service_pb2 as ensemble__service__pb2


class EnsembleOperatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestStatus = channel.unary_unary(
            "/convergedcomputing.org.grpc.v1.EnsembleOperator/RequestStatus",
            request_serializer=ensemble__service__pb2.StatusRequest.SerializeToString,
            response_deserializer=ensemble__service__pb2.StatusResponse.FromString,
        )


class EnsembleOperatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EnsembleOperatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RequestStatus": grpc.unary_unary_rpc_method_handler(
            servicer.RequestStatus,
            request_deserializer=ensemble__service__pb2.StatusRequest.FromString,
            response_serializer=ensemble__service__pb2.StatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "convergedcomputing.org.grpc.v1.EnsembleOperator", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class EnsembleOperator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/convergedcomputing.org.grpc.v1.EnsembleOperator/RequestStatus",
            ensemble__service__pb2.StatusRequest.SerializeToString,
            ensemble__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
