# permissions for end users to edit ensembles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ensemble-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ensemble-operator
    app.kubernetes.io/part-of: ensemble-operator
    app.kubernetes.io/managed-by: kustomize
  name: ensemble-editor-role
rules:
- apiGroups:
  - ensemble.flux-framework.org
  resources:
  - ensembles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ensemble.flux-framework.org
  resources:
  - ensembles/status
  verbs:
  - get
