ARG tag=22.04
FROM ubuntu:${tag}

LABEL maintainer="Vanessasaurus <@vsoch>"

RUN apt-get update && apt-get install -y git

# We don't install python or the library here - it needs to be installed
# with the same python that flux uses in the shared init view
WORKDIR /code
COPY . /code
