ARG tag=9
FROM rockylinux:${tag}

LABEL maintainer="Vanessasaurus <@vsoch>"

RUN dnf update -y && dnf install -y git

# We don't install python or the library here - it needs to be installed
# with the same python that flux uses in the shared init view
WORKDIR /code
COPY . /code
