apiVersion: ensemble.flux-framework.org/v1alpha1
kind: Ensemble
metadata:
  name: workload-demand
spec:  
  members:
  - sidecar:
      pullAlways: true
      image: ghcr.io/converged-computing/ensemble-operator-api:rockylinux9

    # Algorithm and options:
    # terminateChecks says to terminate after 2 subsequent inactive status checks
    algorithm:
      name: workload-demand
      options:
        terminateChecks: 2
        scaleUpChecks: 4

    # I made these the size of the cluster so we trigger scaling at least once
    jobs:
      - name: lammps-2
        command: lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
        count: 5
        nodes: 2
      - name: lammps-4
        command: lmp -v x 4 -v y 4 -v z 4 -in in.reaxc.hns -nocite
        count: 2
        nodes: 2

    minicluster:
      spec:
        size: 2
        maxSize: 6
        minSize: 2

        # This is a list because a pod can support multiple containers
        containers:
        - image: ghcr.io/converged-computing/metric-lammps:latest

          # You can set the working directory if your container WORKDIR is not correct.
          workingDir: /opt/lammps/examples/reaxff/HNS